services:
  - type: web
    name: hianime-api
    runtime: docker
    repo: https://github.com/ryanwtf88/hianime-api
    region: oregon
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Add your other environment variables here
      # - key: UPSTASH_REDIS_REST_URL
      #   sync: false
      # - key: UPSTASH_REDIS_REST_TOKEN
      #   sync: false
    buildFilter:
      paths:
        - "**/*.js"
        - "**/*.ts"
        - package.json
        - bun.lockb
        - Dockerfile
    autoDeploy: true
